"""Marche extra (flip IT: elettronica, utensili, moda, casa, bellezza, sport)."""

# Niente parole inglesi generiche (next, only, gap come token isolato corto).
EXTRA_BRANDS: tuple[str, ...] = (
    # Elettronica / audio / foto / smart home
    "apple",
    "oneplus",
    "oppo",
    "realme",
    "vivo",
    "motorola",
    "nokia",
    "nothing",
    "fairphone",
    "honor",
    "meizu",
    "zte",
    "tcl",
    "hisense",
    "haier",
    "grundig",
    "thomson",
    "toshiba",
    "panasonic",
    "jvc",
    "pioneer",
    "denon",
    "marantz",
    "onkyo",
    "yamaha",
    "harman kardon",
    "infinity",
    "klipsch",
    "polk",
    "bowers wilkins",
    "bang olufsen",
    "b&o",
    "devialet",
    "nad",
    "cambridge audio",
    "audioengine",
    "ifi",
    "fiio",
    "ibasso",
    "hifiman",
    "audeze",
    "focal",
    "grado",
    "beyerdynamic",
    "akg",
    "audio technica",
    "rode",
    "blue yeti",
    "elgato",
    "razer kraken",
    "hyperx cloud",
    "astro",
    "scuf",
    "nacon",
    "hori",
    "8bitdo",
    "powera",
    "pdp",
    "nyko",
    "mayflash",
    "steam deck",
    "valve",
    "oculus",
    "meta quest",
    "pico",
    "htc vive",
    "playstation vr",
    "nintendo switch",
    "retroid",
    "anbernic",
    "ayaneo",
    "onexplayer",
    "gpd",
    "lenovo legion",
    "alienware",
    "razer blade",
    "gigabyte",
    "aorus",
    "clevo",
    "framework",
    "surface",
    "microsoft",
    "intel",
    "amd",
    "nvidia",
    "geforce",
    "radeon",
    "corsair vengeance",
    "g.skill",
    "kingston fury",
    "crucial",
    "samsung ssd",
    "wd black",
    "seagate firecuda",
    "synology",
    "qnap",
    "terra master",
    "asustor",
    "drobo",
    "lacie",
    "owc",
    "samsung t7",
    "sandisk extreme",
    "lexar",
    "transcend",
    "pny",
    "adata",
    "patriot",
    "teamgroup",
    "silicon power",
    "intenso",
    "verbatim",
    "emtec",
    "integral",
    "kingston canvas",
    "sony tough",
    "prograde",
    "angelbird",
    "atomos",
    "blackmagic",
    "red digital",
    "arri",
    "panasonic lumix",
    "olympus",
    "om system",
    "pentax",
    "leica",
    "hasselblad",
    "phase one",
    "sigma",
    "tamron",
    "tokina",
    "samyang",
    "rokinon",
    "voigtlander",
    "zeiss",
    "manfrotto",
    "gitzo",
    "benro",
    "sirui",
    "joby",
    "peak design",
    "lowepro",
    "think tank",
    "billingham",
    "domke",
    "godox",
    "profoto",
    "broncolor",
    "elinchrom",
    "neewer",
    "aputure",
    "nanlite",
    "smallrig",
    "tilta",
    "dji osmo",
    "dji mini",
    "dji air",
    "dji mavic",
    "dji avata",
    "autel",
    "skydio",
    "holy stone",
    "potensic",
    "gopro hero",
    "insta360 x",
    "insta360 go",
    "akaso",
    "sjcam",
    "yi camera",
    "kodak",
    "polaroid",
    "fujifilm instax",
    "canon pixma",
    "epson",
    "brother",
    "hp officejet",
    "xerox",
    "kyocera",
    "ricoh",
    "okidata",
    "dymo",
    "zebra",
    "labelwriter",
    "wacom",
    "huion",
    "xp-pen",
    "gaomon",
    "veikk",
    "ugee",
    "remarkable",
    "kindle oasis",
    "kindle paperwhite",
    "kobo clara",
    "kobo libra",
    "kobo sage",
    "pocketbook",
    "onyx boox",
    "supernote",
    "tolino",
    "likebook",
    "meebook",
    "bigme",
    "hisense a9",
    "tcl nxtpaper",
    "boox palma",
    "garmin fenix",
    "garmin forerunner",
    "garmin instinct",
    "garmin vivoactive",
    "garmin venu",
    "garmin edge",
    "coros pace",
    "coros apex",
    "polar vantage",
    "polar ignite",
    "suunto 9",
    "suunto vertical",
    "amazfit gtr",
    "amazfit gts",
    "amazfit bip",
    "amazfit t-rex",
    "huawei watch",
    "huawei band",
    "samsung galaxy watch",
    "samsung galaxy buds",
    "samsung galaxy tab",
    "xiaomi redmi",
    "xiaomi poco",
    "xiaomi mi band",
    "xiaomi watch",
    "haylou",
    "soundpeats",
    "qcy",
    "tozo",
    "earfun",
    "soundcore",
    "anker soundcore",
    "tronsmart",
    "ugreen",
    "baseus",
    "spigen",
    "otterbox",
    "tech21",
    "uag",
    "caseology",
    "ringke",
    "esr",
    "nomad",
    "pitaka",
    "casetify",
    "dbrand",
    "mophie",
    "belkin boost",
    "anker nano",
    "anker powercore",
    "ravpower",
    "aukey",
    "choetech",
    "inomata",
    "native union",
    "twelve south",
    "satechi",
    "hyper",
    "caldigit",
    "owc thunderbolt",
    "plugable",
    "startech",
    "cable matters",
    "deleycon",
    "goobay",
    "hama",
    "trust",
    "speedlink",
    "sharkoon",
    "fractal",
    "nzxt",
    "lian li",
    "be quiet",
    "noctua",
    "arctic",
    "cooler master",
    "thermaltake",
    "phanteks",
    "deepcool",
    "silverstone",
    "in win",
    "bitfenix",
    "cougar",
    "msi mag",
    "asus tuf",
    "asus rog",
    "gigabyte aorus",
    "evga",
    "zotac",
    "palit",
    "inno3d",
    "gainward",
    "sapphire",
    "powercolor",
    "xfx",
    "asrock",
    "biostar",
    "supermicro",
    "dell",
    "optiplex",
    "latitude",
    "precision",
    "thinkpad",
    "ideapad",
    "yoga",
    "macbook",
    "imac",
    "ipad",
    "airpods",
    "homepod",
    "chromecast",
    "google nest",
    "amazon echo",
    "echo dot",
    "echo show",
    "fire tv",
    "fire tablet",
    "kindle fire",
    "roku",
    "apple tv",
    "nvidia shield",
    "xiaomi stick",
    "mi box",
    "formuler",
    "zgemma",
    "vu plus",
    "dreambox",
    "octagon",
    "gigablue",
    "sky q",
    "tivusat",
    "humax",
    "strong",
    "digitalbox",
    "edision",
    "televes",
    "fritzbox",
    "avm",
    "devolo",
    "powerline",
    "ubiquiti",
    "unifi",
    "mikrotik",
    "cisco",
    "linksys",
    "d-link",
    "tenda",
    "mercure",
    "mercusys",
    "asus zenwifi",
    "eero",
    "google wifi",
    "orbi",
    "velop",
    "synology rt",
    "gl.inet",
    "gl inet",
    "openwrt",
    "raspberry pi",
    "arduino",
    "esp32",
    "nvidia jetson",
    "intel nuc",
    "beelink",
    "minisforum",
    "gmtec",
    "chuwi",
    "teclast",
    "alldocube",
    "blackview",
    "umidigi",
    "doogee",
    "cubot",
    "oukitel",
    "ulefone",
    "iiiif150",
    "agmmobile",
    "cat phones",
    "rugged",
    "crosscall",
    "gigaset",
    "alcatel",
    "wiko",
    "brondi",
    "doro",
    "emporia",
    "swisstone",
    "myphone",
    "logicom",
    "spc",
    "kruger matz",
    "overmax",
    "navitel",
    "mio dashcam",
    "nextbase",
    "vantrue",
    "viofo",
    "70mai",
    "70 mai",
    "finevu",
    "blackvue",
    "thinkware",
    "rexing",
    "apeman",
    "akaso brave",
    "yi dashcam",
    "garmin dash cam",
    "tomtom",
    "garmin nuvi",
    "navman",
    "mio spirit",
    "blaupunkt",
    "kenwood car",
    "pioneer avh",
    "alpine",
    "jvc kw",
    "sony xav",
    "focal car",
    "jl audio",
    "kicker",
    "rockford fosgate",
    "hertz audio",
    "audison",
    "helix",
    "ground zero",
    "esx",
    "match audio",
    "mosconi",
    "bitten",
    "stinger",
    "scosche",
    "metra",
    "pac audio",
    "iDatalink",
    "idatalink",
    "connects2",
    "parrot",
    "bose car",
    "burmester",
    "bang olufsen car",
    # Utensili / fai da te / giardino
    "bosch professional",
    "bosch home",
    "makita lxt",
    "dewalt xr",
    "milwaukee m18",
    "milwaukee m12",
    "hikoki multi volt",
    "metabo powermaxx",
    "festool c18",
    "fein",
    "flex power tools",
    "rupes",
    "mirka",
    "dynabrade",
    "ingco",
    "total tools",
    "worx nitro",
    "worx Landroid",
    "greenworks",
    "ego power",
    "stihl",
    "husqvarna",
    "echo tools",
    "shindaiwa",
    "honda power",
    "yamaha generator",
    "kipor",
    "hyundai power",
    "einhell power x-change",
    "parkside performance",
    "lidl parkside",
    "ferrex",
    "workzone",
    "silverline",
    "draper",
    "sealey",
    "clarke",
    "sip industrial",
    "jet tools",
    "powermatic",
    "laguna",
    "sawstop",
    "dewalt flexvolt",
    "ridgid",
    "craftsman",
    "porter cable",
    "black decker",
    "stanley fatmax",
    "irwin",
    "lenox",
    "diablo",
    "freud",
    "cmmt",
    "cmt",
    "bosch expert",
    "makita white",
    "norske",
    "forrest",
    "incra",
    "kreg",
    "trend routing",
    "tormek",
    "work sharp",
    "spyderco",
    "victorinox",
    "wenger",
    "leatherman",
    "gerber",
    "sog",
    "mora",
    "opinel",
    "cold steel",
    "benchmade",
    "kizer",
    "civivi",
    "we knife",
    "crkt",
    "kershaw",
    "buck knives",
    "case xx",
    "truper",
    "truper expert",
    "bahco",
    "sandvik",
    "facom s.a.s",
    "sam outillage",
    "beta utencil",
    "usag stanley",
    "gedore",
    "stahlwille",
    "hazet",
    "ks tools",
    "kraftwerk",
    "proxxon",
    "wera zyklop",
    "wiha",
    "pb swiss",
    "knipex cobra",
    "knipex pliers wrench",
    "nws",
    "orbis",
    "bessey",
    "irwin quick-grip",
    "wolfcraft",
    "trotec",
    "scheppach",
    "holzmann",
    "metabo hpt",
    "hitachi",
    "hikoki hitachi",
    "panasonic ey",
    "aeg powertools",
    "ryobi one+",
    "ozito",
    "bauer",
    "hercules",
    "warrior",
    "central pneumatic",
    "chicago electric",
    "earthwise",
    "sun joe",
    "snow joe",
    "worx hydroshot",
    "karcher k2",
    "karcher k4",
    "karcher k5",
    "karcher k7",
    "nilfisk",
    "lavor",
    "stihl re",
    "bosch aquatak",
    "black+decker pressure",
    "alta",
    "compa",
    "fervi",
    "telwin",
    "deca",
    "selco",
    "lincoln electric",
    "esab",
    "kemppi",
    "fronius",
    "miller weld",
    "hobart",
    "forney",
    "lotos",
    "yeswelder",
    "arccaptain",
    "yeswelder",
    "sican",
    "magnum",
    "helvi",
    "cemont",
    "gys",
    "telwin inversione",
    "einhell generator",
    "hyundai generator",
    "powerplus",
    "varo",
    "scheppach generator",
    "kipor generator",
    "honda eu",
    "yamaha ef",
    "briggs stratton",
    "kohler",
    "loncin",
    "lifan",
    "champion power",
    "westinghouse generator",
    "duromax",
    "firman",
    "pulsar",
    "a-ipower",
    "wacker neuson",
    "bomag",
    "atlas copco",
    "ingram",
    "ingco industrial",
    "total industrial",
    "emak",
    "oleo-mac",
    "efco",
    "castelgarden",
    "mountfield",
    "al-ko",
    "solo by al-ko",
    "stiga",
    "mcculloch",
    "partner",
    "poulan",
    "homelite",
    "ryobi garden",
    "greenworks pro",
    "ego mower",
    "segway navimow",
    "worx landroid",
    "gardena",
    "husqvarna automower",
    "honda mower",
    "john deere",
    "kubota",
    "yanmar",
    "iseki",
    "new holland",
    "case ih",
    "fendt",
    "claas",
    "massey ferguson",
    "same deutz",
    "lamborghini trattori",
    "antonio carraro",
    "goldoni",
    "pasquali",
    "bcs",
    "ferrari trattori",
    "grillo",
    "bertolini",
    "pubert",
    "mtd",
    "cub cadet",
    "troy bilt",
    "ariens",
    "toro",
    "lawn boy",
    "snapper",
    "weber barbecue",
    "weber genesis",
    "weber spirit",
    "weber q",
    "napoleon grill",
    "broil king",
    "char-broil",
    "oklahoma joe",
    "traeger",
    "pit boss",
    "camp chef",
    "green mountain",
    "recteq",
    "kamado joe",
    "big green egg",
    "primo ceramic",
    "komodo kamado",
    "monolith grill",
    "often",
    "ofyr",
    "magma",
    "cadac",
    "outwell",
    "easy camp",
    "vango",
    "berghaus",
    "the north face",
    "patagonia",
    "arc'teryx",
    "arcteryx",
    "mammut",
    "salewa",
    "dynafit",
    "la sportiva",
    "scarpa",
    "merrell",
    "keen",
    "teva",
    "chaco",
    "birkenstock",
    "crocs",
    "havaianas",
    "ipanema",
    "rider",
    "melissa",
    "ugg",
    "sorel",
    "moon boot",
    "tecnica",
    "nordica",
    "rossignol",
    "salomon alpine",
    "atomic",
    "head ski",
    "fischer",
    "volkl",
    "k2",
    "line skis",
    "faction",
    "armada",
    "black crows",
    "dynastar",
    "elán",
    "elan",
    "blizzard",
    "lange",
    "dalbello",
    "full tilt",
    "tecnica mach",
    "burton",
    "ride snowboard",
    "gnu",
    "lib tech",
    "capita",
    "jones snowboards",
    "nitro snowboard",
    "rome sds",
    "yes snowboard",
    "bataleon",
    "union bindings",
    "burton cartels",
    "now bindings",
    "flux",
    "arbor",
    "never summer",
    "dakine",
    "anon",
    "oakley snow",
    "smith optics",
    "giro",
    "poc",
    "sweet protection",
    "uvex",
    "julbo",
    "cebe",
    "bolle",
    "spy optic",
    "dragon alliance",
    "vonzipper",
    "electric",
    "shred optics",
    "scott sports",
    "camelbak",
    "osprey",
    "deuter",
    "lowe alpine",
    "gregory",
    "mystery ranch",
    "tasmanian tiger",
    "5.11",
    "511 tactical",
    "maxpedition",
    "helikon",
    "direct action",
    "crye",
    "arc'teryx leaf",
    "patagonia prow",
    "fjallraven kanken",
    "kanken",
    "herschel",
    "eastpak",
    "jansport",
    "nike sb",
    "vans old skool",
    "converse chuck",
    "new balance 574",
    "new balance 550",
    "new balance 990",
    "asics gel",
    "hoka clifton",
    "hoka bondi",
    "hoka speedgoat",
    "on cloud",
    "on cloudmonster",
    "brooks ghost",
    "brooks glycerin",
    "saucony",
    "saucony endorphin",
    "altra",
    "topo athletic",
    "inov-8",
    "inov8",
    "salomon speedcross",
    "salomon sense",
    "la sportiva bushido",
    "hoka challenger",
    "nike pegasus",
    "nike vomero",
    "nike structure",
    "nike zoom",
    "adidas ultraboost",
    "adidas nmd",
    "adidas samba",
    "adidas gazelle",
    "adidas spezial",
    "adidas campus",
    "adidas superstar",
    "adidas stan smith",
    "puma suede",
    "puma rs-x",
    "reebok classic",
    "reebok nano",
    "reebok club c",
    "fila disruptor",
    "fila vintage",
    "diadora",
    "lotto sport",
    "kappa",
    "ellesse",
    "fila",
    "champion",
    "russell athletic",
    "fruit of the loom",
    "gildan",
    "hanes",
    "carhartt wip",
    "dickies",
    "wrangler",
    "lee jeans",
    "levis 501",
    "levis 511",
    "diesel jeans",
    "replay",
    "g-star",
    "g star raw",
    "true religion",
    "ag jeans",
    "paige",
    "citizens of humanity",
    "mother jeans",
    "frame denim",
    "acne studios",
    "nudie jeans",
    "cheap monday",
    "weekday",
    "monki",
    "& other stories",
    "cos",
    "arket",
    "h&m studio",
    "zara",
    "mango",
    "pull bear",
    "bershka",
    "stradivarius",
    "oysho",
    "massimo dutti",
    "lefties",
    "uniqlo",
    "gu",
    "muji",
    "cos stores",
    "weekday",
    "moncler",
    "canada goose",
    "woolrich",
    "peuterrey",
    "save the duck",
    "colmar",
    "k-way",
    "kway",
    "invicta jacket",
    "napapijri",
    "timberland 6 inch",
    "dr martens 1460",
    "solovair",
    "red wing",
    "thursday boots",
    "blundstone",
    "rm williams",
    "clarks",
    "clarks wallabee",
    "geox",
    "hogan",
    "tod's",
    "tods",
    "santoni",
    "church's",
    "john lobb",
    "aldens",
    "alden",
    "trickers",
    "loake",
    "grenson",
    "sebagos",
    "sebago",
    "sperry",
    "gh bass",
    "cole haan",
    "ecco",
    "mephisto",
    "solidus",
    "finn comfort",
    "think shoes",
    "josef seibel",
    "rieker",
    "gabor",
    "caprice",
    "tamaris",
    "marco tozzi",
    "s oliver",
    "s.oliver",
    "esprit",
    "tom tailor",
    "only",
    "vero moda",
    "pieces",
    "selected homme",
    "jack jones",
    "jack & jones",
    "selected",
    "reserved",
    "sinsay",
    "house",
    "cropp",
    "mohito",
    "medicine",
    "4f",
    "outhorn",
    "cropp town",
    "pullandbear",
    "calzedonia",
    "intimissimi",
    "tezenis",
    "yamamay",
    "women secret",
    "women'secret",
    "etam",
    "undiz",
    "oja",
    "victoria secret",
    "victoria's secret",
    "pink nation",
    "calvin klein underwear",
    "tommy jeans",
    "tommy hilfiger",
    "ralph lauren",
    "polo ralph lauren",
    "lacoste",
    "fred perry",
    "ben sherman",
    "barbour",
    "barbour international",
    "pretty green",
    "stone island",
    "cp company",
    "c.p. company",
    "moncler genius",
    "off-white",
    "off white",
    "supreme",
    "palace",
    "stussy",
    "stüssy",
    "bape",
    "a bathing ape",
    "kith",
    "fear of god",
    "essentials fog",
    "gallery dept",
    "rhude",
    "amiri",
    "balenciaga",
    "gucci",
    "louis vuitton",
    "lv",
    "dior",
    "fendi",
    "prada",
    "miumiu",
    "miu miu",
    "bottega veneta",
    "celine",
    "givenchy",
    "saint laurent",
    "ysl",
    "valentino",
    "versace",
    "dolce gabbana",
    "dolce & gabbana",
    "armani exchange",
    "ea7",
    "emporio armani",
    "giorgio armani",
    "hugo boss",
    "boss orange",
    "boss green",
    "canali",
    "zegna",
    "ermenegildo zegna",
    "kiton",
    "brunello cucinelli",
    "loro piana",
    "max mara",
    "maxmara",
    "weekend max mara",
    "marella",
    "sportmax",
    "pennylane",
    "liu jo",
    "liujo",
    "guess",
    "michael kors",
    "coach",
    "kate spade",
    "tory burch",
    "longchamp",
    "furla",
    "coccinelle",
    "guess bags",
    "guess handbags",
    "valentino bags",
    "moschino",
    "love moschino",
    "pinko",
    "pinko love bag",
    "the kooples",
    "maje",
    "sandro",
    "ba&sh",
    "bash",
    "isabel marant",
    "apc",
    "a.p.c.",
    "ami paris",
    "kenzo",
    "comme des garcons",
    "cdg",
    "issey miyake",
    "yohji yamamoto",
    "rick owens",
    "margiela",
    "maison margiela",
    "jil sander",
    "lemaire",
    "the row",
    "toteme",
    "khaite",
    "reformation",
    "ganni",
    "rotate",
    "stine goya",
    "baum und pferdgarten",
    "by malene birger",
    "samsøe",
    "samsoe samsoe",
    "norse projects",
    "our legacy",
    "wood wood",
    "han kjobenhavn",
    "han kjobenhavn",
    "soulland",
    "ganni",
    "acne",
    "jlindeberg",
    "j.lindeberg",
    "peak performance",
    "haglofs",
    "haglöfs",
    "norrøna",
    "norrona",
    "helly hansen",
    "bergans",
    "fjallraven",
    "klattermusen",
    "klättermusen",
    "icebreaker",
    "smartwool",
    "darn tough",
    "falke",
    "stance",
    "bombas",
    "injinji",
    "wrightsock",
    "thorlo",
    "balega",
    "cep",
    "compressport",
    "skins",
    "2xu",
    "under armour",
    "nike pro",
    "adidas climacool",
    "lululemon",
    "alo yoga",
    "girlfriend collective",
    "outdoor voices",
    "vuori",
    "rhone",
    "tracksmith",
    "satisfy running",
    "janji",
    "patagonia capilene",
    "arc'teryx atom",
    "the north face nuptse",
    "columbia omni",
    "marmot",
    "mountain hardwear",
    "rab",
    "montane",
    "outdoor research",
    "black diamond",
    "petzl",
    "grivel",
    "camp",
    "beal",
    "edelrid",
    "mammut climbing",
    "la sportiva climbing",
    "scarpa instinct",
    "five ten",
    "evolv",
    "tenaya",
    "unparallel",
    "mad rock",
    "so iLL",
    "soill",
    "ocun",
    "red chili",
    "boreal",
    "simond",
    "quechua mh",
    "forclaz trek",
    "kalenji kiprun",
    "kipsta football",
    "kipsta",
    "artengo tennis",
    "perfly",
    "solognac",
    "caperlan",
    "tribord",
    "orenbay",
    "nabaiji",
    "arena",
    "speedo",
    "tyr",
    "funkita",
    "funkyshunks",
    "mp michael phelps",
    "aqua sphere",
    "cressi",
    "mares",
    "scubapro",
    "apeeks",
    "apeks",
    "suunto d5",
    "garmin descent",
    "shearwater",
    "oceanic",
    "atomic aquatics",
    "tusa",
    "seac",
    "beuchat",
    "ist",
    "hollis",
    "halcyon",
    "dive rite",
    "zeagle",
    "oms",
    "scubapro seawing",
    "cressi golia",
    "mares x-stream",
    "fourth element",
    "waterproof",
    "scubapro everflex",
    "bare",
    "whites",
    "seaskin",
    "roho",
    "tyrant",
    "rip curl",
    "billabong",
    "quiksilver",
    "roxy",
    "oneill",
    "o'neill",
    "hurley",
    "volcom",
    "element skate",
    "dc shoes",
    "etnies",
    "emerica",
    "lakai",
    "es skate",
    "globe",
    "supra",
    "vans skate",
    "nike sb dunk",
    "adidas skate",
    "new balance numeric",
    "converse cons",
    "spitfire wheels",
    "bones wheels",
    "independent trucks",
    "thunder trucks",
    "tensor",
    "venture trucks",
    "ace trucks",
    "independent stage 11",
    "santacruz",
    "santa cruz",
    "powell peralta",
    "creature",
    "anti hero",
    "antihero",
    "baker skateboards",
    "deathwish",
    "zero skateboards",
    "almost",
    "plan b",
    "girl skateboards",
    "chocolate skateboards",
    "real skateboards",
    "element brand",
    "enjoi",
    "blind skateboards",
    "world industries",
    "zero",
    "birdhouse",
    "tony hawk",
    "berrics",
    "thrasher",
    "transworld",
    "skate mental",
    "welcome skateboards",
    "there skateboards",
    "palace skateboards",
    "fucking awesome",
    "supreme skate",
    "huf",
    "diamond supply",
    "primitive",
    "dgk",
    "krooked",
    "real",
    "antihero",
    "independent",
    "spitfire",
    "bones bearings",
    "bones swiss",
    "ricta",
    "oj wheels",
    "mini logo",
    "mob grip",
    "grizzly grip",
    "jessup",
    "shake junt",
    "bronson",
    "reds bearings",
    "swiss ceramic",
    # Casa / cucina / piccoli elettrodomestici
    "smeg",
    "kitchenaid artisan",
    "kitchenaid mini",
    "kenwood cooking chef",
    "kenwood kmix",
    "kenwood chef",
    "bosch mum",
    "braun mq",
    "braun identity",
    "philips airfryer",
    "philips hue",
    "philips sonicare",
    "oral-b genius",
    "oral b io",
    "waterpik",
    "panasonic ew",
    "panasonic nanoe",
    "rowenta silence force",
    "rowenta air force",
    "rowenta steam",
    "tefal ingenio",
    "tefal actiFry",
    "tefal optigrill",
    "moulinex companion",
    "moulinex cuisine companion",
    "magimix cook expert",
    "magimix 5200",
    "thermomix tm6",
    "thermomix tm5",
    "vorwerk thermomix",
    "bimby tm6",
    "monsieur cuisine",
    "lidl monsieur cuisine",
    "silvercrest",
    "ambiano",
    "nutribullet pro",
    "nutribullet 900",
    "vitamix 5200",
    "vitamix a3500",
    "blendtec",
    "ninja foodi",
    "ninja blender",
    "ninja creami",
    "ninja dual brew",
    "breville barista",
    "breville oracle",
    "breville bambino",
    "sage barista",
    "sage oracle",
    "sage bambino",
    "delonghi magnifica",
    "delonghi dina",
    "delonghi dedica",
    "delonghi rivelia",
    "saeco xelsis",
    "saeco gran aroma",
    "gaggia classic",
    "gaggia magenta",
    "gaggia accademia",
    "lavazza a modo mio",
    "lavazza jolie",
    "nespresso vertuo",
    "nespresso essenza",
    "nespresso citiz",
    "nespresso lattissima",
    "nescafe dolce gusto",
    "dolce gusto",
    "illy x7",
    "illy y3",
    "bialetti moka",
    "bialetti venus",
    "bialetti mukka",
    "alessi 9090",
    "alessi pulcina",
    "alessi juicy salif",
    "bodum",
    "hario",
    "chemex",
    "aeropress",
    "fellow",
    "baratza",
    "eureka mignon",
    "mahlkonig",
    "mahlkönig",
    "compak",
    "mazzer",
    "fiorenzato",
    "ceado",
    "macap",
    "quamar",
    "anfim",
    "la marzocco",
    "slayer espresso",
    "synesso",
    "kees van der westen",
    "rocket espresso",
    "profitec",
    "ecm",
    "bezzera",
    "expobar",
    "rancilio",
    "rancilio silvia",
    "la pavoni",
    "lilit",
    "lelit",
    "lelit mara",
    "lelit elizabeth",
    "quick mill",
    "isomac",
    "faema",
    "cimbali",
    "nuova simonelli",
    "victoria arduino",
    "sanremo coffee",
    "astoria",
    "wega",
    "brasilia",
    "carimali",
    "spaziale",
    "la cimbali",
    "rancilio classe",
    "jura",
    "jura e8",
    "jura s8",
    "jura z10",
    "melitta caffeo",
    "melitta barista",
    "siemens eq",
    "siemens eq.9",
    "bosch vervelle",
    "miele cm",
    "miele cva",
    "aeg kkk",
    "whirlpool w",
    "hotpoint ariston",
    "indesit",
    "candy",
    "hoover h-dry",
    "beko",
    "grundig gkn",
    "hisense fridge",
    "haier fridge",
    "smeg fridge",
    "liebherr",
    "gaggenau",
    "neff",
    "siemens studioLine",
    "bosch serie",
    "miele generation",
    "aeg 9000",
    "electrolux",
    "zanussi",
    "ignis",
    "rex electrolux",
    "baumatic",
    "cata",
    "elica",
    "falmec",
    "best",
    "faber",
    "franke",
    "blanco",
    "smeg hood",
    "barazza",
    "fulgor",
    "ilve",
    "officine gullo",
    "lacanche",
    "wolf range",
    "sub-zero",
    "cove",
    "thermador",
    "bosch benchmark",
    "jennair",
    "kitchenaid architect",
    "ge profile",
    "cafe appliances",
    "samsung bespoke",
    "lg instaview",
    "lg thinq",
    "whirlpool w collection",
    "maytag",
    "amana",
    "frigidaire",
    "kenmore",
    "speed queen",
    "miele w1",
    "miele t1",
    "asko",
    "ascol",
    "v-zug",
    "vzug",
    "gorenje",
    "pelgrim",
    "atag",
    "boretti",
    "smeg portofino",
    "smeg victoria",
    "bertazzoni",
    "officine gullo",
    "la cornue",
    "aga",
    "everhot",
    "esse",
    "stoves",
    "belling",
    "leisure",
    "hotpoint",
    "indesit innex",
    "candy rapido",
    "haier i-pro",
    "hisense washing",
    "tcl washing",
    "beko harvestfresh",
    "dyson v15",
    "dyson v12",
    "dyson v11",
    "dyson v8",
    "dyson outsize",
    "dyson gen5",
    "dyson airwrap",
    "dyson supersonic",
    "dyson corrale",
    "dyson purifier",
    "dyson humidifier",
    "dyson lightcycle",
    "shark stratos",
    "shark detect",
    "shark anti hair wrap",
    "shark wandvac",
    "shark flexstyle",
    "shark beauty",
    "bissell crosswave",
    "bissell pet",
    "bissell spotclean",
    "hoover h-free",
    "hoover h-pacs",
    "rowenta x-plorer",
    "rowenta explorer",
    "irobot roomba",
    "irobot braava",
    "ecovacs deebot",
    "ecovacs winbot",
    "roborock s8",
    "roborock q",
    "roborock s7",
    "dreame l10s",
    "dreame x40",
    "dreame l20",
    "xiaomi vacuum",
    "xiaomi mijia",
    "switchbot",
    "eufy robovac",
    "eufy clean",
    "narwal",
    "yeedi",
    "ilife",
    "proscenic",
    "lefant",
    "honiture",
    "tesvor",
    "bagotte",
    "goovi",
    "tikom",
    "laresar",
    "ultenic",
    "moosoo",
    "vactidy",
    "airrobo",
    "360 s9",
    "viomi",
    "roidmi",
    "jimmy jv",
    "jimmy vacuum",
    "tineco",
    "tineco floor one",
    "tineco pure one",
    "bissell spinwave",
    "karcher vc",
    "karcher fc",
    "nilfisk elite",
    "miele complete",
    "miele blizzard",
    "sebo",
    "numatic",
    "henry vacuum",
    "hetty",
    "numatic henry",
    "kirby",
    "rainbow vacuum",
    "filter queen",
    "simplicity vacuum",
    "riccar",
    "aerus",
    "electrolux pure",
    "aeg fx9",
    "aeg qx",
    "bosch unlimited",
    "siemens vs",
    "philips speedpro",
    "philips 8000",
    "electrolux well q",
    "lg cordzero",
    "samsung jet",
    "dreame t20",
    "dreame t30",
    "xiaomi g10",
    "roborock dyad",
    "tineco ifloor",
    "bissell hydrosteam",
    "vileda steam",
    "vileda looper",
    "swiffer wetjet",
    "swiffer duster",
    "mr. clean",
    "mr clean",
    "cif",
    "ajax",
    "viakal",
    "calgonit",
    "finish",
    "fairy",
    "dash",
    "ariel",
    "persil",
    "skip",
    "lenor",
    "comfort",
    "coccolino",
    "downy",
    "gain",
    "tide",
    "vanish",
    "ace bleach",
    "amuchina",
    "lysol",
    "clorox",
    "harpic",
    "duck toilet",
    "wc net",
    "bref",
    "air wick",
    "glade",
    "febreze",
    "ambipur",
    "ambipur",
    "yankee candle",
    "woodwick",
    "bath body works",
    "bath & body works",
    "diptyque",
    "jo malone",
    "byredo",
    "le labo",
    "aesop",
    "creed aventus",
    "parfums de marly",
    "maison francis kurkdjian",
    "mfk",
    "initio",
    "xerjoff",
    "amouage",
    "roja dove",
    "clive christian",
    "tom ford oud",
    "tom ford lost cherry",
    "dior sauvage",
    "chanel bleu",
    "chanel coco",
    "chanel n5",
    "chanel chance",
    "gucci bloom",
    "gucci guilty",
    "ysl libre",
    "ysl y",
    "armani code",
    "armani acqua di gio",
    "versace eros",
    "versace dylan blue",
    "dolce gabbana light blue",
    "dolce gabbana the one",
    "prada luna rossa",
    "prada amber",
    "hermes terre",
    "hermes twilly",
    "cartier declaration",
    "bvlgari",
    "bulgari",
    "montblanc legend",
    "montblanc explorer",
    "hugo boss bottled",
    "ck one",
    "ck be",
    "davidoff cool water",
    "azzaro wanted",
    "azzaro chrome",
    "paco rabanne 1 million",
    "paco rabanne invictus",
    "paco rabanne lady million",
    "jpg le male",
    "jean paul gaultier",
    "mugler alien",
    "mugler angel",
    "lancôme la vie est belle",
    "lancome idole",
    "lancome tressor",
    "estee lauder",
    "estee lauder advanced night",
    "clinique",
    "clinique moisture surge",
    "mac cosmetics",
    "nars",
    "urban decay",
    "too faced",
    "benefit",
    "tarte",
    "fenty beauty",
    "rare beauty",
    "charlotte tilbury",
    "pat mcgrath",
    "hourglass",
    "westman atelier",
    "saie",
    "glossier",
    "the ordinary",
    "the inkey list",
    "cerave",
    "la roche posay",
    "vichy",
    "avene",
    "avène",
    "eucerin",
    "bioderma",
    "uriage",
    "isdin",
    "svr",
    "ducray",
    "klorane",
    "mustela",
    "weleda",
    "nuxe",
    "caudalie",
    "clarins",
    "sisley",
    "skinceuticals",
    "drunk elephant",
    "tatcha",
    "sunday riley",
    "paula's choice",
    "paulas choice",
    "ordinary",
    "the ordinary niacinamide",
    "cosrx",
    "beauty of joseon",
    "laneige",
    "innisfree",
    "etude house",
    "innisfree",
    "missha",
    "some by mi",
    "purito",
    "isntree",
    "anua",
    "skin1004",
    "round lab",
    "mixsoon",
    "haruharu",
    "axis-y",
    "axis y",
    "medicube",
    "mediheal",
    "dr jart",
    "dr.jart",
    "cosrx snail",
    "klairs",
    "benton",
    "iunik",
    "heimish",
    "banila co",
    "clio",
    "peripera",
    "romand",
    "3ce",
    "wakemake",
    "dasique",
    "hince",
    "amuse",
    "fwee",
    "lilybyred",
    "etude",
    "innisfree green tea",
    "sulwhasoo",
    "amorepacific",
    "hera",
    "i'm from",
    "im from",
    "beauty of joseon relief",
    "anua heartleaf",
    "skin1004 madagascar",
    "round lab dokdo",
    "isntree hyaluronic",
    "purito centella",
    "cosrx advanced snail",
    "the ordinary hyaluronic",
    "cerave moisturising",
    "cerave foaming",
    "la roche posay effaclar",
    "la roche posay cicaplast",
    "vichy mineral 89",
    "avene cicalfate",
    "eucerin hyaluron",
    "bioderma sensibio",
    "uriage bariederm",
    "nuxe huile prodigieuse",
    "caudalie vinoperfect",
    "clarins double serum",
    "estee lauder double wear",
    "mac studio fix",
    "nars radiant creamy",
    "fenty pro filt'r",
    "rare beauty soft pinch",
    "charlotte tilbury airbrush",
    "benefit porefessional",
    "urban decay all nighter",
    "too faced better than sex",
    "tarte shape tape",
    "maybelline",
    "maybelline lash sensational",
    "maybelline fit me",
    "loreal",
    "l'oreal",
    "loreal paris",
    "loreal infallible",
    "nyx",
    "nyx professional",
    "rimmel",
    "rimmel london",
    "max factor",
    "revlon",
    "covergirl",
    "elf cosmetics",
    "e.l.f.",
    "wet n wild",
    "essence",
    "catrice",
    "kiko",
    "kiko milano",
    "pupa",
    "pupa milano",
    "collistar",
    "diego dalla palma",
    "nabla",
    "mulac",
    "neve cosmetics",
    "wycon",
    "sephora collection",
    "ulta",
    "boots no7",
    "no7",
    "simple skincare",
    "neutrogena",
    "aveeno",
    "johnson baby",
    "johnsons",
    "pampers",
    "huggies",
    "prenatal",
    "chicco",
    "artsana",
    "mam",
    "nuk",
    "avent",
    "philips avent",
    "medela",
    "spectra",
    "elvie",
    "willow pump",
    "lansinoh",
    "tommee tippee",
    "dr brown",
    "dr. brown's",
    "nuby",
    "mamade",
    "bibi",
    "difrax",
    "twistshake",
    "beaba",
    "babymoov",
    "badabulle",
    "safety 1st",
    "safety first",
    "angelcare",
    "owlet",
    "nanit",
    "motorola baby",
    "vtech baby",
    "infant optics",
    "hello baby",
    "lollipop camera",
    "cubo ai",
    "eufy spaceview",
    "maxicosi",
    "maxi-cosi",
    "maxi cosi",
    "cybex cloud",
    "cybex sirona",
    "cybex priam",
    "cybex balios",
    "cybex eezy",
    "cybex solution",
    "cybex pallas",
    "britax",
    "britax romer",
    "britax römer",
    "joie",
    "joie i-spin",
    "nuna",
    "nuna pipa",
    "nuna mixx",
    "nuna triv",
    "uppababy",
    "uppababy vista",
    "uppababy cruz",
    "uppababy mesa",
    "bugaboo",
    "bugaboo fox",
    "bugaboo bee",
    "bugaboo donkey",
    "bugaboo butterfly",
    "stokke xplory",
    "stokke yoyo",
    "babyzen yoyo",
    "yoyo",
    "babyzen",
    "inglesina aptica",
    "inglesina electa",
    "inglesina quid",
    "peg perego book",
    "peg perego viaggio",
    "peg perego primo viaggio",
    "peg perego gt4",
    "jané",
    "jane",
    "jané muum",
    "casualplay",
    "bebeconfort",
    "bébé confort",
    "safety 1st",
    "graco",
    "chicco bravo",
    "chicco keyfit",
    "chicco kory",
    "chicco next2me",
    "chicco baby hug",
    "cam il mondo del bambino",
    "cam",
    "foppapedretti",
    "brevi",
    "chicco polly",
    "stokke tripp trapp",
    "stokke sleepi",
    "leander",
    "babybjorn",
    "babybjörn",
    "baby bjorn",
    "ergobaby",
    "tula",
    "lillebaby",
    "boba",
    "manduca",
    "didymos",
    "storchenwiege",
    "hoppediz",
    "lenny lamb",
    "lennylamb",
    "artipoppe",
    "wildbird",
    "sakura bloom",
    "integra baby",
    "connecta",
    "boba wrap",
    "moby wrap",
    "boppy",
    "my brest friend",
    "frida baby",
    "fridababy",
    "nose frida",
    "owlet sock",
    "nanit pro",
    "ihealth",
    "braun thermoscan",
    "braun ntf",
    "withings",
    "omron",
    "beurer",
    "microlife",
    "and medical",
    "a&d medical",
    "rossmax",
    "yuwell",
    "pulse oximeter",
    "wellue",
    "masimo",
    "nonin",
    "resmed",
    "philips dreamstation",
    "resmed airsense",
    "fisher paykel",
    "lowestein",
    "löwenstein",
    "devilibss",
    "devilbiss",
    "invacare",
    "drive medical",
    "sunrise medical",
    "ottobock",
    "ottobock",
    "fillauer",
    "ossur",
    "ossür",
    "thuasne",
    "medi",
    "bauerfeind",
    "donjoy",
    "mcdavid",
    "lp support",
    "rehband",
    "cep compression",
    "2xu compression",
    "skins compression",
    "under armour recovery",
    "hyperice",
    "theragun",
    "therabody",
    "hypervolt",
    "massage gun",
    "renpho",
    "bob and brad",
    "opove",
    "ekrin",
    "addaday",
    "triggerpoint",
    "tp therapy",
    "foam roller",
    "blackroll",
    "grid roller",
    "compex",
    "powerdot",
    "marc pro",
    "normatec",
    "rapid recharge",
    "whoop",
    "oura",
    "oura ring",
    "fitbit charge",
    "fitbit versa",
    "fitbit sense",
    "fitbit inspire",
    "garmin vivosmart",
    "garmin vívosmart",
    "apple watch",
    "apple watch ultra",
    "apple watch se",
    "samsung galaxy watch ultra",
    "google pixel watch",
    "pixel watch",
    "amazfit balance",
    "amazfit active",
    "huawei watch gt",
    "huawei watch ultimate",
    "honor watch",
    "xiaomi watch 2",
    "redmi watch",
    "cmf watch",
    "nothing watch",
    "oneplus watch",
    "oppo watch",
    "realme watch",
    "ticwatch",
    "mobvoi",
    "fossil gen",
    "fossil hybrid",
    "skagen",
    "michael kors access",
    "emporio armani connected",
    "diesel on",
    "guess connect",
    "tissot t-touch",
    "tissot prx",
    "tissot seastar",
    "tissot gentleman",
    "tissot chrono xl",
    "tissot everytime",
    "certina",
    "mido",
    "hamilton khaki",
    "hamilton jazzmaster",
    "longines hydroconquest",
    "longines conquest",
    "longines presence",
    "omega seamaster",
    "omega speedmaster",
    "omega constellation",
    "tag heuer",
    "tag heuer carrera",
    "tag heuer aquaracer",
    "breitling",
    "breitling navitimer",
    "breitling superocean",
    "iwc",
    "iwc mark",
    "iwc portugieser",
    "jaeger lecoultre",
    "jlc",
    "panerai",
    "panerai luminor",
    "panerai radiomir",
    "hublot",
    "hublot big bang",
    "audemars piguet",
    "ap royal oak",
    "patek philippe",
    "patek nautilus",
    "vacheron constantin",
    "roleX",
    "rolex",
    "rolex submariner",
    "rolex datejust",
    "rolex explorer",
    "rolex gmt",
    "rolex daytona",
    "rolex oyster",
    "tudor",
    "tudor black bay",
    "tudor pelagos",
    "tudor ranger",
    "orís",
    "oris",
    "oris aquis",
    "oris divers",
    "sinn",
    "sinn u50",
    "sinn 104",
    "nomos",
    "nomos tangente",
    "nomos club",
    "junghans",
    "junghans max bill",
    "stowa",
    "laco",
    "archimede",
    "glashutte",
    "glashütte original",
    "a lange",
    "a. lange sohne",
    "lang & sohne",
    "iwc schaffhausen",
    "blancpain",
    "blancpain fifty fathoms",
    "breguet",
    "jaquet droz",
    "piaget",
    "cartier tank",
    "cartier santos",
    "cartier ballon bleu",
    "cartier panthere",
    "jaeger-lecoultre reverso",
    "grand seiko",
    "seiko presage",
    "seiko 5",
    "seiko prospex",
    "seiko astron",
    "seiko kinetic",
    "citizen eco-drive",
    "citizen promaster",
    "citizen tsuyosa",
    "orient bambino",
    "orient kamasu",
    "orient star",
    "orient mako",
    "orient ray",
    "casio edifice",
    "casio pro trek",
    "casio protrek",
    "casio g-shock",
    "casio baby-g",
    "casio vintage",
    "casio a168",
    "casio f91w",
    "casio f-91w",
    "casio dw5600",
    "casio ga2100",
    "casio ga-2100",
    "casio gm2100",
    "g-shock ga",
    "g-shock dw",
    "g-shock gw",
    "g-shock rangeman",
    "g-shock mudmaster",
    "g-shock frogman",
    "timex weekender",
    "timex expedition",
    "timex marlin",
    "timex waterbury",
    "timex q",
    "timex ironman",
    "swatch sistem51",
    "swatch moonswatch",
    "omega x swatch",
    "swatch bioceramic",
    "swatch original",
    "swatch irony",
    "swatch skin",
    "tissot pr 100",
    "tissot le locle",
    "tissot powermatic",
    "fossil grant",
    "fossil machine",
    "fossil neutra",
    "fossil copeland",
    "fossil carraway",
    "michael kors lexington",
    "michael kors bradshaw",
    "michael kors runway",
    "armani exchange watch",
    "emporio armani watch",
    "diesel watch",
    "guess watch",
    "tommy hilfiger watch",
    "hugo boss watch",
    "calvin klein watch",
    "skagen watch",
    "daniel wellington",
    "dw watch",
    "cluse",
    "mvmt",
    "mvmt watches",
    "nixon",
    "nixon 51-30",
    "nixon time teller",
    "nixon sentry",
    "admiral",
    "ice-watch",
    "ice watch",
    "ice-glam",
    "flik flak",
    "endura",
    "luminox",
    "luminox navy seal",
    "luminox bear grylls",
    "victorinox i.n.o.x.",
    "victorinox inox",
    "victorinox alliance",
    "wenger watch",
    "swiss military",
    "swiss military hanowa",
    "hanowa",
    "festina",
    "lotus watch",
    "viceroy",
    "marea",
    "time force",
    "police watch",
    "breil",
    "breil tribe",
    "sector",
    "sector no limits",
    "morellato",
    "brosway",
    "2jewels",
    "ops objects",
    "opsobjects",
    "liu jo watch",
    "guess jev",
    "invicta pro diver",
    "invicta bolt",
    "invicta specialty",
    "bulova",
    "bulova lunar pilot",
    "bulova precisio",
    "bulova accutron",
    "citizen tsuyosa",
    "orient bambino gen 2",
    "seiko 5 sports",
    "seiko 5 gmt",
    "seiko alpinist",
    "seiko turtle",
    "seiko samurai",
    "seiko monster",
    "seiko skx",
    "seiko presage cocktail",
    "grand seiko snowflake",
    "grand seiko heritage",
    "casio oceanus",
    "casio wave ceptor",
    "casio lineage",
    "casio mtp",
    "casio ltp",
    "citizen ny",
    "citizen nb",
    "citizen aw",
    "timex mk1",
    "timex allied",
    "timex fairfield",
    "swatch big bold",
    "swatch squba",
    "swatch flymagic",
    # Giocattoli / LEGO / videogiochi / libri
    "lego technic",
    "lego star wars",
    "lego city",
    "lego friends",
    "lego ninjago",
    "lego harry potter",
    "lego marvel",
    "lego disney",
    "lego creator",
    "lego architecture",
    "lego ideas",
    "lego art",
    "lego botanicals",
    "lego icons",
    "lego speed champions",
    "lego duplo",
    "lego classic",
    "mega bloks",
    "mega construx",
    "playmobil",
    "playmobil city",
    "playmobil pirates",
    "schleich",
    "papo",
    "collecta",
    "britains",
    "hot wheels",
    "matchbox",
    "maisto",
    "bburago",
    "burago",
    "siku",
    "wiking",
    "herpa",
    "minichamps",
    "autoart",
    "kyosho",
    "tamiya",
    "revell",
    "italeri",
    "airfix",
    "hasegawa",
    "academy models",
    "trumpeter",
    "meng",
    "takom",
    "border model",
    "bandai",
    "bandai spirites",
    "bandai namco",
    "gunpla",
    "gundam",
    "pokemon",
    "pokémon",
    "pokemon tcg",
    "magic the gathering",
    "mtg",
    "yu-gi-oh",
    "yugioh",
    "one piece card",
    "lorcana",
    "flesh and blood",
    "digimon tcg",
    "weiss schwarz",
    "dragon ball super",
    "cardfight vanguard",
    "funko pop",
    "funko",
    "hot toys",
    "sideshow",
    "iron studios",
    "prime 1",
    "xm studios",
    "kotobukiya",
    "good smile",
    "nendoroid",
    "figma",
    "sh figuarts",
    "mafex",
    "medicom",
    "bearbrick",
    "kubrick",
    "hasbro",
    "mattel",
    "fisher-price",
    "fisher price",
    "little tikes",
    "step2",
    "vtech",
    "leapfrog",
    "melissa doug",
    "melissa & doug",
    "haba",
    "bruder",
    "ravensburger",
    "clementoni",
    "lisciani",
    "headu",
    "djeco",
    "janod",
    "vilac",
    " moulin roty",
    "moulin roty",
    "corolle",
    "gotz",
    "gotz dolls",
    "zapf",
    "baby born",
    "nenuco",
    "nancy doll",
    "barbie",
    "monster high",
    "lol surprise",
    "lol dolls",
    "rainbow high",
    "bratz",
    "american girl",
    "our generation",
    "sylvanian families",
    "calico critters",
    "play-doh",
    "play doh",
    "kinetic sand",
    "orbeez",
    "slime",
    "nerf",
    "nerf elite",
    "nerf ultra",
    "x-shot",
    "boomco",
    "laser x",
    "nerf super soaker",
    "water war",
    "scalextric",
    "carrera go",
    "carrera digital",
    "ninco",
    "slot.it",
    "flyslot",
    "nsr slot",
    "thunderslot",
    "policar",
    "hornby",
    "lima",
    "roco",
    "fleischmann",
    "marklin",
    "märklin",
    "trix",
    "pico",
    "faller",
    "kibri",
    "noch",
    "busch",
    "preiser",
    "woodland scenics",
    "kato",
    "tomix",
    "bachmann",
    "athelarn",
    "athearn",
    "broadway limited",
    "mth",
    "lionel",
    "lego trains",
    "brio",
    "brio world",
    "haba wooden",
    "janod wooden",
    "plan toys",
    "plantoys",
    "grimm's",
    "grimms",
    "grimm",
    "tender leaf",
    "le toy van",
    "bigjigs",
    "melissa doug wooden",
    "ikea lek",
    "mula",
    "duplo",
    "mega bloks first builders",
    "knex",
    "k'nex",
    "geomag",
    "magformers",
    "connetix",
    "picasso tiles",
    "magnatiles",
    "magna-tiles",
    "plus plus",
    "plusplus",
    "nanoblock",
    "nanoblocks",
    "capseals",
    "nintendo switch oled",
    "nintendo switch lite",
    "nintendo 3ds",
    "nintendo 2ds",
    "nintendo wii u",
    "nintendo wii",
    "gamecube",
    "n64",
    "snes",
    "nes",
    "game boy",
    "gameboy",
    "game boy advance",
    "gba",
    "nintendo ds",
    "playstation 5",
    "ps5",
    "ps5 slim",
    "ps5 pro",
    "playstation 4",
    "ps4",
    "ps4 pro",
    "playstation 3",
    "ps3",
    "playstation vita",
    "ps vita",
    "psp",
    "xbox series x",
    "xbox series s",
    "xbox one",
    "xbox one x",
    "xbox 360",
    "steam deck oled",
    "asus rog ally",
    "rog ally",
    "rog ally x",
    "lenovo legion go",
    "legion go",
    "msi claw",
    "ayaneo 2",
    "ayaneo kun",
    "onexplayer 2",
    "gpd win",
    "gpd win mini",
    "ayn odin",
    "retroid pocket",
    "anbernic rg",
    "miyoo mini",
    "powkiddy",
    "trimui",
    "analogue pocket",
    "analogue nt",
    "analogue super nt",
    "analogue mega sg",
    "polymega",
    "mister fpga",
    "evercade",
    "atari vcs",
    "atari 2600",
    "sega genesis",
    "sega mega drive",
    "sega saturn",
    "sega dreamcast",
    "sega game gear",
    "neo geo",
    "neogeo",
    "snk",
    "capcom",
    "square enix",
    "final fantasy",
    "nintendo amiibo",
    "amiibo",
    "skylanders",
    "disney infinity",
    "lego dimensions",
    "ring fit",
    "labo",
    "nintendo labo",
    "joy-con",
    "joycon",
    "dualsense",
    "dualshock",
    "xbox elite",
    "xbox elite 2",
    "scuf reflex",
    "scuf vantage",
    "razer wolverine",
    "razer kishi",
    "backbone",
    "gamesir",
    "8bitdo ultimate",
    "8bitdo pro",
    "powera fusion",
    "nacon revolution",
    "thrustmaster t300",
    "thrustmaster t248",
    "thrustmaster t818",
    "thrustmaster t-gt",
    "fanatec",
    "fanatec csl",
    "fanatec clubsport",
    "fanatec dd",
    "logitech g29",
    "logitech g923",
    "logitech g pro racing",
    "logitech g920",
    "moza racing",
    "moza r5",
    "moza r9",
    "moza r12",
    "simagic",
    "simucube",
    "vrs",
    "asetek simsports",
    "heusbink",
    "heusinkveld",
    "fanatec v2.5",
    "sparco",
    "omp",
    "sabelt",
    "recaro",
    "bride seats",
    "nrg seats",
    "playseat",
    "next level racing",
    "nlr",
    "gt omega",
    "trak racer",
    "asimov",
    "asimov racing",
    "sim-lab",
    "simlab",
    "profile racing",
    "advanced sim racing",
    "asr",
    "rigmetal",
    "8020",
    "80/20",
    "logitech flight",
    "thrustmaster t16000m",
    "thrustmaster warthog",
    "thrustmaster tca",
    "virpil",
    "vkb",
    "vkb gunfighter",
    "winwing",
    "honeycomb",
    "honeycomb alpha",
    "honeycomb bravo",
    "logitech yoke",
    "saitek",
    "ch products",
    "ch fighterstick",
    "turtle beach recon",
    "turtle beach stealth",
    "steelseries arctis",
    "steelseries apex",
    "steelseries rival",
    "steelseries qck",
    "razer blackwidow",
    "razer deathadder",
    "razer viper",
    "razer basilisk",
    "razer huntsman",
    "razer naga",
    "logitech g pro",
    "logitech g502",
    "logitech g915",
    "logitech g733",
    "logitech g305",
    "logitech mx",
    "logitech mx master",
    "logitech mx keys",
    "logitech pebble",
    "microsoft sculpt",
    "microsoft surface keyboard",
    "keychron",
    "keychron k",
    "keychron q",
    "keychron v",
    "nuphy",
    "nuphy air",
    "akko",
    "gmmk",
    "glorious",
    "glorious model o",
    "glorious gmmk",
    "ducky",
    "ducky one",
    "leopold",
    "hhkb",
    "happy hacking",
    "realforce",
    "topre",
    "vortexrace",
    "vortex pok3r",
    "ikbc",
    "anne pro",
    "royal kludge",
    "rk royal kludge",
    "redragon",
    "redragon kumara",
    "redragon k552",
    "aula",
    "magegee",
    "motospeed",
    "epomaker",
    "gateron",
    "cherry mx",
    "kailh",
    "outemu",
    "zealios",
    "holy panda",
    "boba u4",
    "gateron oil king",
    "akko cs",
    "jwk",
    "durock",
    "c3 equalz",
    "gateron milky",
    "ws morandi",
    "drop ctrl",
    "drop alt",
    "drop entrée",
    "olkb",
    "planck",
    "preonic",
    "ergodox",
    "ergodox ez",
    "moonlander",
    "kyria",
    "corne",
    "crkbd",
    "lily58",
    "sofle",
    "iris keyboard",
    "dactyl",
    "kinesis",
    "kinesis advantage",
    "kinesis 360",
    "glove80",
    "zsa",
    "zsa voyager",
    "zsa moonlander",
    "zsa ergodox",
    "microsoft natural",
    "kensington expert",
    "kensington slimblade",
    "evoluent",
    "anker vertical",
    "logitech lift",
    "logitech ergo",
    "mx vertical",
    "razer pro click",
    "keychron m",
    "pulsar x2",
    "pulsar xlite",
    "endgame gear",
    "endgame xm",
    "zowie",
    "zowie ec",
    "zowie fk",
    "zowie za",
    "benq zowie",
    "vaxee",
    "lamzu",
    "lamzu atlantis",
    "finalmouse",
    "finalmouse starlight",
    "ultralight",
    "g wolves",
    "gwolves",
    "xtrfy",
    "xtrfy m4",
    "xtrfy mz1",
    "fnatic",
    "fnatic bolt",
    "rog keris",
    "rog chakram",
    "asus rog strix",
    "asus tuf gaming",
    "msi gek",
    "msi claw 8",
    "gigabyte aero",
    "aorus 15",
    "razer blade 14",
    "razer blade 16",
    "alienware m16",
    "alienware x16",
    "dell g16",
    "dell g15",
    "hp omen",
    "hp victus",
    "lenovo loq",
    "lenovo legion 5",
    "lenovo legion 7",
    "acer predator",
    "acer nitro",
    "acer swift",
    "asus zenbook",
    "asus vivobook",
    "asus expertbook",
    "samsung galaxy book",
    "microsoft surface laptop",
    "microsoft surface pro",
    "microsoft surface go",
    "google pixelbook",
    "chromebook",
    "framework 13",
    "framework 16",
    "starlabs",
    "starlite",
    "pine64",
    "pinephone",
    "pinenote",
    "clockworkpi",
    "clockwork pi",
    "devterm",
    "uconsole",
    "pocketchip",
    "nextbook",
    "chuwi minibook",
    "gpd pocket",
    "gpd p2 max",
    "one netbook",
    "onenetbook",
    "onegx",
    "topton",
    "beelink ser",
    "beelink eq",
    "beelink mini s",
    "minisforum um",
    "minisforum em",
    "gmtec nucbox",
    "intel nuc 13",
    "intel nuc 12",
    "asus pn",
    "asus expertcenter",
    "lenovo thinkcentre",
    "hp elitedesk",
    "hp prodesk",
    "dell optiplex micro",
    "mac mini",
    "mac studio",
    "mac pro",
    "imac 24",
    "imac 27",
    "macbook air",
    "macbook pro",
    "macbook air m2",
    "macbook air m3",
    "macbook pro m3",
    "macbook pro m4",
    "ipad pro",
    "ipad air",
    "ipad mini",
    "ipad 10",
    "apple pencil",
    "magic keyboard",
    "magic mouse",
    "airtag",
    "airtags",
    "homepod mini",
    "apple watch series",
    "vision pro",
    "apple vision",
    "samsung tab s9",
    "samsung tab s10",
    "samsung tab a9",
    "lenovo tab",
    "lenovo p12",
    "xiaomi pad",
    "xiaomi pad 6",
    "xiaomi pad 7",
    "redmi pad",
    "honor pad",
    "oppo pad",
    "oneplus pad",
    "realme pad",
    "amazon fire hd",
    "fire hd 10",
    "fire hd 8",
    "kindle scribe",
    "kindle colorsoft",
    "kobo elipsa",
    "kobo libra colour",
    "kobo clara colour",
    "onyx boox note",
    "onyx boox tab",
    "onyx palma",
    "remarkable 2",
    "remarkable paper pro",
    "supernote a5",
    "supernote a6",
    "ratta supernote",
    "bigme b7",
    "bigme inknote",
    "hisense a9",
    "hisense a7",
    "tcl 50 nxtpaper",
    "boox go",
    "pocketbook inkpad",
    "pocketbook verse",
    "tolino vision",
    "tolino shine",
    "likebook mars",
    "meebook p78",
    "dasung",
    "dasung paperlike",
    "onyx boox palma 2",
)
