"""Riconoscimento marca (substring + fuzzy) su titoli sporchi."""

from __future__ import annotations

import re
from difflib import SequenceMatcher

BRANDS: tuple[str, ...] = (
    "casio",
    "g-shock",
    "fossil",
    "seiko",
    "timex",
    "tissot",
    "citizen",
    "orient",
    "swatch",
    "invicta",
    "garmin",
    "polar",
    "suunto",
    "coros",
    "wahoo",
    "xiaomi",
    "huawei",
    "amazfit",
    "fitbit",
    "samsung",
    "sony",
    "bose",
    "jbl",
    "anker",
    "belkin",
    "logitech",
    "razer",
    "hyperx",
    "corsair",
    "sennheiser",
    "shure",
    "edifier",
    "nintendo",
    "sega",
    "lego",
    "playmobil",
    "chicco",
    "peg perego",
    "cybex",
    "inglesina",
    "stokke",
    "kenwood",
    "smeg",
    "kitchenaid",
    "philips",
    "rowenta",
    "braun",
    "bosch",
    "siemens",
    "tefal",
    "moulinex",
    "delonghi",
    "nutribullet",
    "ninja",
    "karcher",
    "dyson",
    "irobot",
    "makita",
    "dewalt",
    "milwaukee",
    "stanley",
    "hikoki",
    "festool",
    "metabo",
    "einhell",
    "ryobi",
    "worx",
    "dremel",
    "knipex",
    "wera",
    "facom",
    "beta",
    "usag",
    "parkside",
    "nike",
    "adidas",
    "puma",
    "vans",
    "converse",
    "new balance",
    "asics",
    "reebok",
    "under armour",
    "the north face",
    "columbia",
    "patagonia",
    "zara",
    "uniqlo",
    "guess",
    "calvin klein",
    "tommy hilfiger",
    "levis",
    "coach",
    "michael kors",
    "longchamp",
    "furla",
    "eastpak",
    "kipling",
    "samsonite",
    "oakley",
    "ray-ban",
    "persol",
    "chanel",
    "dior",
    "lancome",
    "estee lauder",
    "nivea",
    "nuxe",
    "cerave",
    "vichy",
    "kiko",
    "maybelline",
    "gillette",
    "oral-b",
    "panasonic",
    "sharp",
    "whirlpool",
    "hotpoint",
    "indesit",
    "gopro",
    "dji",
    "insta360",
    "kindle",
    "kobo",
    "canon",
    "nikon",
    "fujifilm",
    "sandisk",
    "kingston",
    "seagate",
    "tp-link",
    "netgear",
    "eufy",
    "arlo",
    "osram",
    "ikea",
    "alessi",
    "zwilling",
    "le creuset",
    "bialetti",
    "nespresso",
    "lavazza",
    "illy",
    "krups",
    "saeco",
    "gaggia",
    "ariete",
    "thule",
    "osprey",
    "decathlon",
    "quechua",
    "domyos",
    "technogym",
    "shimano",
    "specialized",
    "trek",
    "bianchi",
    "asus",
    "acer",
    "lenovo",
    "msi",
    "hp",
    "google",
    "daniel wellington",
    "cluse",
    "black+decker",
    "audio-technica",
    "western digital",
    "la roche posay",
    "the ordinary",
    "yves saint laurent",
    "hermes",
    "prada",
    "versace",
    "armani",
    "diesel",
    "superdry",
    "carhartt",
    "timberland",
    "dr martens",
    "crocs",
    "salomon",
    "merrell",
    "hoka",
    "on running",
    "lululemon",
    "helly hansen",
    "mammut",
    "fjallraven",
    "osram",
    "philips hue",
    "nanoleaf",
    "ring",
    "nest",
    "sonos",
    "marshall",
    "ultimate ears",
    "beats",
    "skullcandy",
    "jabra",
    "plantronics",
    "steelseries",
    "turtle beach",
    "thrustmaster",
    "logitech g",
    "razer",
    "black+decker",
    "black and decker",
    "aeg",
    "miele",
    "electrolux",
    "candy",
    "hoover",
    "vorwerk",
    "folletto",
    "bimby",
    "thermomix",
    "sage",
    "breville",
    "magimix",
    "vitamix",
    "kitchenaid",
    "zwilling",
    "wusthof",
    "global knives",
    "le creuset",
    "staub",
    "emile henry",
    "pyrex",
    "tupperware",
    "sistema",
    "locknlock",
    "joseph joseph",
    "oxo",
    "brabantia",
    "simplehuman",
    "dyson",
    "shark",
    "bissell",
    "vileda",
    "swiffer",
    "febreze",
    "air wick",
    "yankee candle",
    "diptyque",
    "jo malone",
    "creed",
    "tom ford",
    "yves rocher",
    "l'occitane",
    "the body shop",
    "rituals",
    "zara home",
    "h&m",
    "massimo dutti",
    "bershka",
    "pull&bear",
    "stradivarius",
    "pull and bear",
    "oysho",
    "lefties",
    "decathlon",
    "quechua",
    "forclaz",
    "kalenji",
    "btwin",
    "rockrider",
    "van rysel",
    "triban",
    "domyos",
    "artengo",
    "outshock",
    "kipsta",
    "solognac",
    "caperlan",
    "nakamura",
    "btwin",
)

SHORT_BRANDS: tuple[str, ...] = ("hp", "lg", "3m", "jbl")


def _norm(text: str) -> str:
    lowered = text.lower().replace("_", " ")
    lowered = re.sub(r"[^a-z0-9+&' -]+", " ", lowered)
    return re.sub(r"\s+", " ", lowered).strip()


_BRANDS_NORM: tuple[str, ...] = tuple(dict.fromkeys(_norm(brand) for brand in BRANDS if len(_norm(brand)) >= 3))
_SHORT_NORM: tuple[str, ...] = tuple(dict.fromkeys(_norm(brand) for brand in SHORT_BRANDS))


def find_brand(title: str) -> str | None:
    text = _norm(title)
    if not text:
        return None
    for brand in sorted(_BRANDS_NORM, key=len, reverse=True):
        if re.search(rf"(?<![a-z0-9]){re.escape(brand)}(?![a-z0-9])", text):
            return brand
    for brand in _SHORT_NORM:
        if re.search(rf"(?<![a-z0-9]){re.escape(brand)}(?![a-z0-9])", text):
            return brand
    tokens = [token for token in text.split() if len(token) >= 5]
    best: tuple[float, str] | None = None
    for brand in _BRANDS_NORM:
        if " " in brand:
            continue
        for token in tokens:
            ratio = SequenceMatcher(None, token, brand).ratio()
            if ratio >= 0.88 and (best is None or ratio > best[0]):
                best = (ratio, brand)
    return best[1] if best else None
